version: '3.8'

networks:
  web:
    external: true

services:
  core-connektiv8-com:
    restart: always
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    image: connektiv8/connektkiv8-base-docker-forge-template:${TAG:-latest}
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.core-connektiv8-com.entrypoints=https
      - traefik.http.routers.core-connektiv8-com.rule=Host(`${TRAEFIK_HOST:-core.connektiv8.com}`)
      - traefik.http.routers.core-connektiv8-com.service=core-connektiv8-com
      - traefik.http.services.core-connektiv8-com.loadbalancer.server.port=80
      - traefik.http.routers.core-connektiv8-com.tls.certresolver=leresolver
