version: '3'

networks:
  web:
    external: true

services:
  example-docker-forge:
    restart: always
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    image: ijpatricio/example-docker-forge:${TAG:-latest}
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.example-docker-forge.entrypoints=https
      - traefik.http.routers.example-docker-forge.rule=Host(`${TRAEFIK_HOST:-forge-docker-app.jpat.dev}`)
      - traefik.http.routers.example-docker-forge.service=example-docker-forge
      - traefik.http.services.example-docker-forge.loadbalancer.server.port=80
      - traefik.http.routers.example-docker-forge.tls.certresolver=leresolver
